# Generated by Django 5.2 on 2025-04-16 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datastores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField(blank=True)),
                ('instance_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datastore_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('datastore_name', models.CharField(max_length=100)),
                ('private_permissions', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('accessed_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Buckets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.IntegerField()),
                ('bucket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bucket_name', models.CharField(max_length=100)),
                ('private_permissions', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('accessed_at', models.DateTimeField()),
                ('datastore_id', models.ForeignKey(db_column='datastore_id', on_delete=django.db.models.deletion.CASCADE, to='bb_app.datastores')),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('owner_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('private_permissions', models.BooleanField(default=True)),
                ('file_path', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('accessed_at', models.DateTimeField()),
                ('bucket_id', models.ForeignKey(db_column='bucket_id', on_delete=django.db.models.deletion.CASCADE, to='bb_app.buckets')),
                ('datastore_id', models.ForeignKey(db_column='datastore_id', on_delete=django.db.models.deletion.CASCADE, to='bb_app.datastores')),
            ],
        ),
    ]
