# Generated by Django 5.1.6 on 2025-02-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfilemodel',
            name='file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
